server:
  bind:
    host: 0.0.0.0
    port: 5000
  url: https://pygeoapi.onrender.com//
  mimetype: application/json; charset=UTF-8
  encoding: utf-8
  gzip: false
  languages:
    # First language is the default language
    - en-US
    - fr-CA
  cors: true
  pretty_print: true
  limits:
    default_items: 20
    max_items: 50
  map:
    url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
    attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
  admin: false # enable admin api

logging:
  level: ERROR
  #logfile: /tmp/pygeoapi.log

metadata:
  identification:
    title:
      en: pygeoapi default instance
      fr: instance par défaut de pygeoapi
    description:
      en: pygeoapi provides an API to geospatial data
      fr: pygeoapi fournit une API aux données géospatiales
    keywords:
      en:
        - geospatial
        - data
        - api
      fr:
        - géospatiale
        - données
        - api
    keywords_type: theme
    terms_of_service: https://creativecommons.org/licenses/by/4.0/
    url: https://example.org
  license:
    name: CC-BY 4.0 license
    url: https://creativecommons.org/licenses/by/4.0/
  provider:
    name: Organization Name
    url: https://pygeoapi.io
  contact:
    name: Lastname, Firstname
    position: Position Title
    address: Mailing Address
    city: City
    stateorprovince: Administrative Area
    postalcode: Zip or Postal Code
    country: Country
    phone: +xx-xxx-xxx-xxxx
    fax: +xx-xxx-xxx-xxxx
    email: you@example.org
    url: Contact URL
    hours: Mo-Fr 08:00-17:00
    instructions: During hours of service. Off on weekends.
    role: pointOfContact

resources:
  espacios_geograficos:
    type: collection
    title: Espacios Geográficos
    description:
      en: Sample metadata
      fr: Exemples
    keywords:
      - espacios
      - geograficos
    language: es
    links:
      - type: text/html
        rel: canonical
        title: data source
        href: https://example.org/link-to-data
        hreflang: es-MX
    extents:
      spatial:
        bbox: [-180, -90, 180, 90]
        crs: http://www.opengis.net/def/crs/OGC/1.3/CRS84
    temporal:
      begin: 2011-11-11
      end: null
    providers:
      - type: feature
        name: PostgreSQL
        data:
          host: dpg-d0k67i3e5dus73bgdq50-a.frankfurt-postgres.render.com
          port: 5432
          dbname: laboratoriosoftware
          user: laboratoriosoft_user
          password: PFy5jAhxVfAkn6FzWHJAHvTEF6VrbROh
          connect_timeout: 10
        id_field: idSpace
        table: spaces
        geom_field: geom

  hello-world:
    type: process
    processor:
      name: HelloWorld

links:
  - type: application/openapi+json;version=3.0
    rel: service-desc
    title: Express API definition
    href: https://back-end-sv3z.onrender.com/openapi.json
